export const GET_IMAGES_ACTION_REQUEST = "GET_IMAGES_ACTION_REQUEST";
export const GET_IMAGES_ACTION_SUCCESS = "GET_IMAGES_ACTION_SUCCESS";
export const GET_IMAGES_ACTION_FAILURE = "GET_IMAGES_ACTION_FAILURE";
export const REFRESH_IMAGES_ACTION_REQUEST = "REFRESH_IMAGES_ACTION_REQUEST";
export const REFRESH_IMAGES_ACTION_REFRESH = "REFRESH_IMAGES_ACTION_REFRESH";
export const REFRESH_IMAGES_ACTION_FAILURE = "REFRESH_IMAGES_ACTION_FAILURE";

