export const REQUEST_ACTION_TYPE = "REQUEST_ACTION_TYPE";
export const SUCCESS_ACTION_TYPE = "REQUEST_ACTION_TYPE";
export const FAILURE_ACTION_TYPE = "REQUEST_ACTION_TYPE";
export const REFRESH_ACTION_TYPE = "REFRESH_ACTION_TYPE";

