export const REFRESH_IMAGES_ACTION_REQUEST = "REFRESH_IMAGES_ACTION_REQUEST";
export const REFRESH_IMAGES_ACTION_REFRESH = "REFRESH_IMAGES_ACTION_REFRESH";
export const REFRESH_IMAGES_ACTION_FAILURE = "REFRESH_IMAGES_ACTION_FAILURE";

